version: "3"
networks:
  selenoid_net:
    external:
      name: selenoid_net
services:
 selenoid:
   container_name: selenoid
   image: "aerokube/selenoid:1.3.7"
   command: -limit 16 -retry-count 1000 -container-network selenoid_net -timeout 1                                                                                                                                                             0m0s
   ports:
     - 4444:4444
   volumes:
     - /selenoid/selenoid:/etc/selenoid:ro
     - /selenoid/selenoid/config:/etc/selenoid/config:ro
     - /var/run/docker.sock:/var/run/docker.sock
   networks:
     - selenoid_net
 selenoid-ui:
   container_name: selenoid-ui
   image: "aerokube/selenoid-ui:1.4.3"
   command: -selenoid-uri 'http://selenoid:4444'
   ports:
     - 8080:8080
   networks:
    - selenoid_net
      # ggr:
      #   restart: always
      #   image: aerokube/ggr
      #   ports:
      #   - "4445:4445"
      #   volumes:
      #   - "/docker/selenoid:/etc/grid-router:ro"
      #   command: ["-quotaDir", "/etc/grid-router"]
      #   networks:
      #   - selenoid_net
      # ggr-ui:
      #   restart: always
      #   image: aerokube/ggr-ui
      #   ports:
      #   - "8889:8889"
      #   volumes:
      #   - "/docker/selenoid:/etc/grid-router/quota:ro"
      #   networks:
      #   - selenoid_net